/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Ticket;
import ec.edu.ups.modelo.Vehiculo;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import ec.edu.ups.controlador.*;
import java.util.ResourceBundle;

/**
 *
 * @author Dutan2000
 */
public class VistaListarTickets extends javax.swing.JInternalFrame {

    private ControladorCliente controladorCliente;
    private ControladorTicket controladorTicket;
    private ControladorVehiculo controladorVehiculo;

    //Tabla
    private String codigo;
    private String fechaIngreso;
    private String fechaSalida;
    private String total;
    private String minutos;
    private String fracciones;
    private String placa;
    private String marca;
    private String modelo;
    private String cedula;
    private String nombre;
    private String direccion;
    private String telefono;
    
    public VistaListarTickets(ControladorCliente controladorCliente, ControladorTicket controladorTicket, ControladorVehiculo controladorVehiculo) {
        initComponents();
        this.controladorCliente = controladorCliente;
        this.controladorTicket = controladorTicket;
        this.controladorVehiculo = controladorVehiculo;
    }

    public void setCambiarIdioma(ResourceBundle mensajes) {
        this.codigo = mensajes.getString("codigo");
        this.fechaIngreso = mensajes.getString("fechaIngreso");
        this.fechaSalida = mensajes.getString("fechaSalida");
        this.total = mensajes.getString("total");
        this.minutos = mensajes.getString("minutos");
        this.fracciones = mensajes.getString("fracciones");
        this.placa = mensajes.getString("placa");
        this.marca = mensajes.getString("marca");
        this.modelo = mensajes.getString("modelo");
        this.cedula = mensajes.getString("cedula");
        this.nombre = mensajes.getString("nombre");
        this.direccion = mensajes.getString("direccion");
        this.telefono = mensajes.getString("telefono");
        listarTickets();
    }
    
    private void listarTickets() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblTickets.getModel();
        modeloTabla.setColumnCount(0);
        modeloTabla.setRowCount(0);
        modeloTabla.addColumn(codigo);
        modeloTabla.addColumn(fechaIngreso);
        modeloTabla.addColumn(fechaSalida);
        modeloTabla.addColumn(total);
        modeloTabla.addColumn(minutos);
        modeloTabla.addColumn(fracciones);
        modeloTabla.addColumn(placa);
        modeloTabla.addColumn(marca);
        modeloTabla.addColumn(modelo);
        modeloTabla.addColumn(cedula);
        modeloTabla.addColumn(nombre);
        modeloTabla.addColumn(direccion);
        modeloTabla.addColumn(telefono);

        this.tblTickets.setModel(modeloTabla);
        Object[] fila = new Object[13];

        for (Ticket datosTicket : controladorTicket.listaGeneralDeTickets()) {
            fila[0] = datosTicket.getNumero();
            fila[1] = fechaActual(datosTicket.getFechaHoraIngreso());
            if (datosTicket.getFechaHoraSalida() != null) {
                fila[2] = fechaActual(datosTicket.getFechaHoraSalida());
            } else {
                fila[2] = "";
            }
            fila[3] = "$ " + datosTicket.getTotal();
            fila[4] = datosTicket.getMinutos();
            fila[5] = datosTicket.getFracciones();
            Vehiculo datosVehiculo = datosTicket.getVehiculoTicket();
            fila[6] = datosVehiculo.getPlaca();
            fila[7] = datosVehiculo.getModelo();
            fila[8] = datosVehiculo.getPlaca();
            fila[9] = datosVehiculo.getCliente().getCedula();
            fila[10] = datosVehiculo.getCliente().getNombre();
            fila[11] = datosVehiculo.getCliente().getDireccion();
            fila[12] = datosVehiculo.getCliente().getTelefono();
            modeloTabla.addRow(fila);
        }
        this.tblTickets.setModel(modeloTabla);
    }

    private String fechaActual(Date fecha) {
        String strDateFormat = "dd-MM-yyyy HH: mm: ss";
        SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);
        return objSDF.format(fecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        tblTickets.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTickets.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblTickets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 938, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        listarTickets();

    }//GEN-LAST:event_formInternalFrameActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTickets;
    // End of variables declaration//GEN-END:variables
}
