/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorTicket;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.dao.ClienteDAO;
import ec.edu.ups.dao.TicketDAO;
import ec.edu.ups.dao.VehiculoDAO;
import ec.edu.ups.idao.IClienteDAO;
import ec.edu.ups.idao.ITicketDAO;
import ec.edu.ups.idao.IVehiculoDAO;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Paul Idrovo
 */
public class VistaPrincipal extends javax.swing.JFrame {

    //Vistas
    private VistaAgregarCliente vistaAgregarCliente;
    private VistaAgregarVehiculo vistaAgregarVehiculo;
    private VistaIngresoParqueadero vistaIngresoParqueadero;
    private VistaSalidaParqueadero vistaSalidaParqueadero;
    private VistaListarTickets vistaListarTickets;
    private VistaEditarDatosVehiculo vistaEditarDatosVehiculo;
    //Dao
    private IClienteDAO clienteDao;
    private ITicketDAO ticketDao;
    private IVehiculoDAO vehiculoDao;
    //Controladores
    private ControladorCliente controladorCliente;
    private ControladorTicket controladorTicket;
    private ControladorVehiculo controladorVehiculo;

    public VistaPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        lblFondo.setSize(screenSize);
        
        //Inicializar Dao
        this.clienteDao = new ClienteDAO();
        this.ticketDao = new TicketDAO();
        this.vehiculoDao = new VehiculoDAO();

        //Inicializar controladores
        this.controladorCliente = new ControladorCliente(clienteDao, ticketDao, vehiculoDao);
        this.controladorTicket = new ControladorTicket(clienteDao, ticketDao, vehiculoDao);
        this.controladorVehiculo = new ControladorVehiculo(clienteDao, ticketDao, vehiculoDao);

        //Vistas
        this.vistaAgregarCliente = new VistaAgregarCliente(controladorCliente, controladorTicket, controladorVehiculo, vistaAgregarVehiculo);
        this.vistaAgregarVehiculo = new VistaAgregarVehiculo(controladorCliente, controladorTicket, controladorVehiculo, vistaAgregarCliente, vistaIngresoParqueadero);
        this.vistaAgregarCliente.setVistaAgregarVehiculo(vistaAgregarVehiculo);
        this.vistaEditarDatosVehiculo = new VistaEditarDatosVehiculo(controladorCliente, controladorTicket, controladorVehiculo, vistaIngresoParqueadero);
        this.vistaIngresoParqueadero = new VistaIngresoParqueadero(controladorCliente, controladorTicket, controladorVehiculo, vistaAgregarVehiculo, vistaEditarDatosVehiculo);
        this.vistaEditarDatosVehiculo.setVistaIngreso(vistaIngresoParqueadero);
        this.vistaAgregarVehiculo.setVistaIngresoParqueadero(vistaIngresoParqueadero);
        this.vistaSalidaParqueadero = new VistaSalidaParqueadero(controladorCliente, controladorTicket, controladorVehiculo);
        this.vistaListarTickets = new VistaListarTickets(controladorCliente, controladorTicket, controladorVehiculo);

        //Agregar desktopPane
        this.desktopPane.add(vistaAgregarCliente);
        this.desktopPane.add(vistaAgregarVehiculo);
        this.desktopPane.add(vistaIngresoParqueadero);
        this.desktopPane.add(vistaSalidaParqueadero);
        this.desktopPane.add(vistaListarTickets);
        this.desktopPane.add(vistaEditarDatosVehiculo);
    }

    private void Ocultar() {
        this.vistaAgregarCliente.setVisible(false);
        this.vistaAgregarVehiculo.setVisible(false);
        this.vistaIngresoParqueadero.setVisible(false);
        this.vistaSalidaParqueadero.setVisible(false);
        this.vistaListarTickets.setVisible(false);
        this.vistaEditarDatosVehiculo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        lblFondo = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnIngresar = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        menuIdioma = new javax.swing.JMenu();
        menuItemEspañol = new javax.swing.JMenuItem();
        menuItemIngles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/hora.png"))); // NOI18N
        desktopPane.add(lblFondo);
        lblFondo.setBounds(630, 10, 30, 30);

        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/parque.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("INICIO");
        fileMenu.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        mnIngresar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/moving-truck.png"))); // NOI18N
        mnIngresar.setMnemonic('o');
        mnIngresar.setText("Ingresar vehiculo");
        mnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIngresarActionPerformed(evt);
            }
        });
        fileMenu.add(mnIngresar);

        saveMenuItem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/enviado.png"))); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Salir vehiculo");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/directorio.png"))); // NOI18N
        jMenuItem1.setText("Listar tickets");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem1);

        exitMenuItem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/cerrar.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuIdioma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/traduccion.png"))); // NOI18N
        menuIdioma.setMnemonic('e');
        menuIdioma.setText("IDIOMA");
        menuIdioma.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        menuItemEspañol.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        menuItemEspañol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/espana.png"))); // NOI18N
        menuItemEspañol.setMnemonic('t');
        menuItemEspañol.setText("Español");
        menuItemEspañol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEspañolActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemEspañol);

        menuItemIngles.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        menuItemIngles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/ups/multimedia/bandera.png"))); // NOI18N
        menuItemIngles.setMnemonic('y');
        menuItemIngles.setText("Ingles");
        menuItemIngles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInglesActionPerformed(evt);
            }
        });
        menuIdioma.add(menuItemIngles);

        menuBar.add(menuIdioma);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void mnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIngresarActionPerformed
        Ocultar();
        this.vistaIngresoParqueadero.setVisible(true);
    }//GEN-LAST:event_mnIngresarActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        Ocultar();
        this.vistaSalidaParqueadero.setVisible(true);
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Ocultar();
        this.vistaListarTickets.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemInglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInglesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemInglesActionPerformed

    private void menuItemEspañolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEspañolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemEspañolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    System.out.println("Error setting Java LAF: " + e);
                }
                new VistaPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuIdioma;
    private javax.swing.JMenuItem menuItemEspañol;
    private javax.swing.JMenuItem menuItemIngles;
    private javax.swing.JMenuItem mnIngresar;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
