/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorTicket;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Ticket;
import ec.edu.ups.modelo.Vehiculo;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Paul Idrovo
 */
public class VistaIngresoParqueadero extends javax.swing.JInternalFrame {

    private ControladorCliente controladorCliente;
    private ControladorTicket controladorTicket;
    private ControladorVehiculo controladorVehiculo;

    private VistaAgregarVehiculo vistaAgregarVehiculo;
    private VistaEditarDatosVehiculo vistaEditarDatosVehiculo;

    //optionPanel
    private String opcionSi;
    private String opcionCancelar;
    private String opcionEditar;
    private String opcion1parte1;
    private String opcion1parte2;
    private String opcion2parte1;
    private String opcion2parte2;
    private String opcionTituloConfirmar;
    private String mensajeTicket;
    private String mensajeErrorPlaca;
    private String tituloErrorDatos;

    //Tabla
    private String codigo;
    private String fechaIngreso;
    private String placa;
    private String marca;
    private String modelo;
    private String cedula;
    private String nombre;
    private String direccion;
    private String telefono;

    public VistaIngresoParqueadero(ControladorCliente controladorCliente, ControladorTicket controladorTicket, ControladorVehiculo controladorVehiculo, VistaAgregarVehiculo vistaAgregarVehiculo, VistaEditarDatosVehiculo vistaEditarDatosVehiculo) {
        initComponents();
        this.controladorCliente = controladorCliente;
        this.controladorTicket = controladorTicket;
        this.controladorVehiculo = controladorVehiculo;
        this.vistaAgregarVehiculo = vistaAgregarVehiculo;
        this.vistaEditarDatosVehiculo = vistaEditarDatosVehiculo;
    }

    public void setCambiarIdioma(ResourceBundle mensajes) {
        this.pnIngresarTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, mensajes.getString("panelIngresarTicket"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); 
        this.lblPlaca.setText(mensajes.getString("placa"));
        this.opcionSi = mensajes.getString("si");
        this.opcionCancelar = mensajes.getString("cancelar");
        this.opcionEditar = mensajes.getString("editar");
        this.opcion1parte1 = mensajes.getString("confirmarPlaca1");
        this.opcion1parte2 = mensajes.getString("confirmarPlaca2");
        this.opcion2parte1 = mensajes.getString("noExistePlaca1");
        this.opcion2parte2 = mensajes.getString("noExistePlaca2");
        this.opcionTituloConfirmar = mensajes.getString("opcionTituloConfirmar");
        this.mensajeTicket = mensajes.getString("creado");
        this.mensajeErrorPlaca = mensajes.getString("mensajeErrorPlaca");
        this.tituloErrorDatos = mensajes.getString("tituloErrorDatos");
        this.codigo = mensajes.getString("codigo");
        this.fechaIngreso = mensajes.getString("fechaIngreso");
        this.placa = mensajes.getString("placa");
        this.marca = mensajes.getString("marca");
        this.modelo = mensajes.getString("modelo");
        this.cedula = mensajes.getString("cedula");
        this.nombre = mensajes.getString("nombre");
        this.direccion = mensajes.getString("direccion");
        this.telefono = mensajes.getString("telefono");
        
        listarTickets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnIngresarTicket = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();
        ftxPlaca = new javax.swing.JFormattedTextField();
        lblPlaca = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pnIngresarTicket.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "INGRESAR TICKET", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 1, 18))); // NOI18N

        tblTickets.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTickets.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tblTickets);
        if (tblTickets.getColumnModel().getColumnCount() > 0) {
            tblTickets.getColumnModel().getColumn(0).setMinWidth(20);
            tblTickets.getColumnModel().getColumn(0).setPreferredWidth(100);
            tblTickets.getColumnModel().getColumn(0).setMaxWidth(200);
            tblTickets.getColumnModel().getColumn(1).setMinWidth(20);
            tblTickets.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblTickets.getColumnModel().getColumn(1).setMaxWidth(200);
            tblTickets.getColumnModel().getColumn(2).setMinWidth(20);
            tblTickets.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblTickets.getColumnModel().getColumn(2).setMaxWidth(200);
            tblTickets.getColumnModel().getColumn(3).setMinWidth(20);
            tblTickets.getColumnModel().getColumn(3).setPreferredWidth(100);
            tblTickets.getColumnModel().getColumn(3).setMaxWidth(200);
        }

        try {
            ftxPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxPlaca.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        ftxPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ftxPlacaKeyTyped(evt);
            }
        });

        lblPlaca.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPlaca.setText("PLACA:");

        javax.swing.GroupLayout pnIngresarTicketLayout = new javax.swing.GroupLayout(pnIngresarTicket);
        pnIngresarTicket.setLayout(pnIngresarTicketLayout);
        pnIngresarTicketLayout.setHorizontalGroup(
            pnIngresarTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1830, Short.MAX_VALUE)
            .addGroup(pnIngresarTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnIngresarTicketLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnIngresarTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1812, Short.MAX_VALUE)
                        .addGroup(pnIngresarTicketLayout.createSequentialGroup()
                            .addComponent(lblPlaca)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ftxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        pnIngresarTicketLayout.setVerticalGroup(
            pnIngresarTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 657, Short.MAX_VALUE)
            .addGroup(pnIngresarTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnIngresarTicketLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnIngresarTicketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPlaca)
                        .addComponent(ftxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnIngresarTicket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnIngresarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
         listarTickets();
         ftxPlaca.setValue("");
    }//GEN-LAST:event_formInternalFrameActivated

    private void ftxPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ftxPlacaKeyTyped
        char validar = evt.getKeyChar();
        if (validar == '\n') {
            if (ftxPlaca.getValue() != null) {
                if (controladorVehiculo.buscarVehiculo(ftxPlaca.getValue().toString()) != null) {
                    //HABLITA VENTANA CON LOS DATOS DE LA PLACA Y SU DUEÑO
                    this.vistaEditarDatosVehiculo.setPlaca(ftxPlaca.getValue().toString());
                    this.vistaEditarDatosVehiculo.setVisible(true);

                    Object[] opcionesJPanel = {opcionSi, opcionEditar, opcionCancelar};
                    int confirmar = JOptionPane.showOptionDialog(null,
                            "<html>" + opcion1parte1 + " <strong>" + ftxPlaca.getValue() + "</strong> " + opcion1parte2 + "</html>",
                            opcionTituloConfirmar,
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.INFORMATION_MESSAGE, null, opcionesJPanel, null);
                    //REGISTRO DE PLACA EXSISTENTE
                    if (JOptionPane.OK_OPTION == confirmar) {
                        this.vistaEditarDatosVehiculo.setVisible(false);
                        Calendar c = Calendar.getInstance();
                        controladorTicket.ingresoVehiculoTicket(c.getTime(), ftxPlaca.getValue().toString());
                        JOptionPane.showMessageDialog(null, "TICKET " + mensajeTicket, "TICKET", JOptionPane.INFORMATION_MESSAGE);
                        listarTickets();
                    } else if (confirmar == 1) {
                        //PERMITE EDITAR LOS DATOS DEL VEHICULO
                        this.setVisible(false);
                    } else {
                        //SE CANCELA EL INGRESO DEL TICKET
                        this.vistaEditarDatosVehiculo.setVisible(false);
                    }
                } else {
                    Object[] opcionesJPanel = {opcionSi, opcionCancelar};
                    int confirmar = JOptionPane.showOptionDialog(null,
                            "<html>" + opcion2parte1 + " <strong>" + ftxPlaca.getValue() + "</strong> " + opcion2parte2 + "</html>",
                            opcionTituloConfirmar,
                            JOptionPane.YES_NO_CANCEL_OPTION,
                            JOptionPane.INFORMATION_MESSAGE, null, opcionesJPanel, null);
                    if (JOptionPane.OK_OPTION == confirmar) {
                        this.setVisible(false);
                        //ENVIA LA VISTA PARA CREAR UN NUEVO VEHICULO
                        vistaAgregarVehiculo.setPlaca(ftxPlaca.getValue());
                        vistaAgregarVehiculo.setVisible(true);
                        ftxPlaca.setValue("");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, mensajeErrorPlaca, tituloErrorDatos, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ftxPlacaKeyTyped
    
    //METODO PARA FORMATO DE TABLA 
    private void listarTickets() {
        DefaultTableModel modeloTabla = (DefaultTableModel) tblTickets.getModel();
        modeloTabla.setColumnCount(0);
        modeloTabla.setRowCount(0);
        modeloTabla.addColumn(codigo);
        modeloTabla.addColumn(fechaIngreso);
        modeloTabla.addColumn(placa);
        modeloTabla.addColumn(marca);
        modeloTabla.addColumn(modelo);
        modeloTabla.addColumn(cedula);
        modeloTabla.addColumn(nombre);
        modeloTabla.addColumn(direccion);
        modeloTabla.addColumn(telefono);

        this.tblTickets.setModel(modeloTabla);
        Object[] fila = new Object[9];

        for (Ticket datosTicket : controladorTicket.listaIngresoDeTickets()) {
            fila[0] = datosTicket.getNumero();
            fila[1] = fechaActual(datosTicket.getFechaHoraIngreso());
            Vehiculo datosVehiculo = datosTicket.getVehiculoTicket();
            fila[2] = datosVehiculo.getPlaca();
            fila[3] = datosVehiculo.getModelo();
            fila[4] = datosVehiculo.getPlaca();
            fila[5] = datosVehiculo.getCliente().getCedula();
            fila[6] = datosVehiculo.getCliente().getNombre();
            fila[7] = datosVehiculo.getCliente().getDireccion();
            fila[8] = datosVehiculo.getCliente().getTelefono();
            modeloTabla.addRow(fila);
        }
        this.tblTickets.setModel(modeloTabla);
    }
    //CAMBIO DE FECHA A CIERTO FORMATO
    private String fechaActual(Date fecha) {
        String strDateFormat = "dd-MM-yyyy HH: mm: ss";
        SimpleDateFormat objSDF = new SimpleDateFormat(strDateFormat);
        return objSDF.format(fecha);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftxPlaca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JPanel pnIngresarTicket;
    private javax.swing.JTable tblTickets;
    // End of variables declaration//GEN-END:variables
}
